const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../build/color/conversions.js'),V=require('../build/color/cvdModels.js'),R=require('../build/stimulus/random.js'),P=require('../build/stimulus/palette.js'),S=require('../build/psychophysics/staircase.js'),A=require('../build/psychophysics/assessment.js'),O=require('../build/optimizer/scoring.js'),G=require('../build/optimizer/candidateGeneration.js'),Store=require('../build/profile/storage.js');
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),vector=(a,b,t=1e-6)=>a.forEach((x,i)=>near(x,b[i],t));
const demo=Store.demoVision();
test('sRGB exact transfer breakpoints and known midpoint',()=>{near(C.srgbToLinear(.04045),.00313080495356,1e-10);near(C.linearToSrgb(.0031308),.040449936,1e-9);near(C.srgbToLinear(.5),.21404114048223,1e-10)});
test('sRGB transfer roundtrips signed values',()=>{for(const v of [-.1,0,.001,.02,.3,.5,.8,1,1.2])near(C.linearToSrgb(C.srgbToLinear(v)),v,1e-7)});
test('linear RGB white to XYZ is D65',()=>vector(C.rgbToXyz([1,1,1]),C.D65));
test('linear red maps to standard XYZ column',()=>vector(C.rgbToXyz([1,0,0]),[.4123907993,.2126390059,.0193308187]));
test('RGB / XYZ roundtrips 100 seeded samples',()=>{const r=R.rng(725);for(let i=0;i<100;i++){const v=[r(),r(),r()];vector(C.xyzToRgb(C.rgbToXyz(v)),v)}});
test('CIELAB D65 white and black references',()=>{vector(C.xyzToLab(C.D65),[100,0,0]);vector(C.xyzToLab([0,0,0]),[0,0,0]);vector(C.labToXyz([100,0,0]),C.D65)});
test('XYZ / Lab roundtrip around toe',()=>{for(const v of [[.001,.003,.005],[.4,.3,.8],[0,0,0]])vector(C.labToXyz(C.xyzToLab(v)),v)});
test('OKLab red reference',()=>vector(C.rgbToOklab([1,0,0]),[.62795536,.22486306,.12584630],1e-7));
test('RGB / OKLab roundtrips 100 seeded samples',()=>{const r=R.rng(375);for(let i=0;i<100;i++){const v=[r(),r(),r()];vector(C.oklabToRgb(C.rgbToOklab(v)),v)}});
test('RGB / HPE-LMS roundtrip including white',()=>{for(const v of [[1,1,1],[1,0,0],[.22,.7,.03]])vector(C.lmsToRgb(C.rgbToLms(v)),v)});
test('color distances symmetric and zero for equality',()=>{near(C.deltaE76([1,2,3],[1,2,3]),0);near(C.deltaEOK([1,2,3],[3,4,5]),C.deltaEOK([3,4,5],[1,2,3]))});
test('all CVD zero-severity models are identity',()=>{for(const k of ['normal','protan','deutan','tritan'])vector(V.simulate([.7,.2,.4],k,0),[.7,.2,.4])});
test('Machado 0.5 deutan reference matrix',()=>vector(V.cvdMatrix('deutan',.5)[0],[.547494,.607765,-.155259]));
test('Machado interpolates adjacent severity matrices',()=>{const a=V.cvdMatrix('deutan',.5),b=V.cvdMatrix('deutan',.6),q=V.cvdMatrix('deutan',.531);for(let i=0;i<3;i++)vector(q[i],a[i].map((v,j)=>v*.69+b[i][j]*.31))});
test('CVD transforms preserve neutral colors within table precision',()=>{for(const k of ['protan','deutan','tritan'])for(const s of [0,.3,.6,.9,1])vector(V.simulate([.4,.4,.4],k,s),[.4,.4,.4],1e-6)});
test('CVD output is not silently clipped before diagnostics',()=>assert.ok(V.simulate([0,0,1],'deutan',1)[0]<0));
test('nonfinite severity rejected and bounds clamped',()=>{assert.throws(()=>V.cvdMatrix('protan',NaN));assert.deepEqual(V.cvdMatrix('deutan',2),V.cvdMatrix('deutan',1))});
test('confusion directions obey equal nominal Y',()=>{for(const k of ['protan','deutan','tritan'])near(C.luminance(V.confusionDirection(k,true)),0,1e-8)});
test('seeded PRNG reproducible and different for distinct seeds',()=>{const a=R.rng(1),b=R.rng(1),c=R.rng(2);const xs=Array.from({length:20},a);assert.deepEqual(xs,Array.from({length:20},b));assert.notDeepEqual(xs,Array.from({length:20},c))});
test('gamut checks flag clipping and NaN',()=>{assert.equal(C.inGamut([-.1,.4,1.1]),false);assert.equal(C.inGamut([NaN,.2,.3]),false);vector(C.clip([-.2,.3,1.1]),[0,.3,1]);near(C.gamutPenalty([-.1,.2,1.1]),.2)});
test('stimulus colors reproduce from seed',()=>{const c=G.candidate(53,demo);assert.deepEqual(P.paletteSamples(c),P.paletteSamples(c));assert.notDeepEqual(P.paletteSamples(c),P.paletteSamples({...c,seed:54}))});
test('equal-Y glyph signal does not encode a luminance step when in gamut',()=>{const c={...G.candidate(44,demo),equalY:true,signal:.018,distraction:.1,luminanceNoise:0};const a=P.makeColor(c,true,.2,.1,0),b=P.makeColor(c,false,.2,.1,0);near(C.luminance(a.rgb),C.luminance(b.rgb),1e-8)});
test('two-down one-up staircase steps and reversals',()=>{let s=S.createStaircase(.1);s=S.advance(s,true);near(s.level,.1);s=S.advance(s,true);assert.ok(s.level<.1);s=S.advance(s,false);assert.equal(s.reversals.length,1);near(s.level,.1)});
test('staircase never reports a threshold with zero reversals',()=>assert.equal(S.threshold('protan',S.createStaircase()).value,null));
test('2AFC link is chance at zero and capped below perfect',()=>{near(A.pCorrect(0,.01),.5);assert.ok(A.pCorrect(100,.01)<1);assert.ok(A.pCorrect(.02,.01)>A.pCorrect(.01,.01))});
test('Wilson interval remains wide for 8/8',()=>{const ci=S.wilson(8,8);assert.ok(ci[0]<.7);near(ci[1],1)});
test('Unicode normalization and exact/free-response matching',()=>{assert.ok(S.exactMatch(' ＡB\nC ','ab c'));assert.ok(S.exactMatch('你好','你好'));assert.equal(S.exactMatch('hey mew','hey meow'),false);assert.ok(S.editSimilarity('hey mew','hey meow')<1)});
test('empty and populated local profiles serialize',()=>{const p={...Store.emptyProfile(),vision:demo};assert.deepEqual(Store.deserialize(Store.serialize(p)).vision,demo);assert.throws(()=>Store.deserialize('{"version":99}'))});
test('malformed severity is rejected on load',()=>{const p={...Store.emptyProfile(),vision:{...demo,severity:2}};assert.throws(()=>Store.deserialize(JSON.stringify(p)))});
test('normal simulated user has no target transformation advantage',()=>{const v={...demo,kind:'normal',severity:0,noise:.018};const c=G.candidate(19,v);const m=O.evaluate(c,v);near(m.differential,0)});
test('CVD-filter adversary equals the target simulation',()=>{const c=G.candidate(1,demo),m=O.evaluate(c,demo);near(m.filterAttack,m.target)});
test('blank signal produces zero model separation',()=>{const c={...G.candidate(52,demo),signal:0};const m=O.evaluate(c,demo);near(m.target,0);near(m.typical,0)});
test('optimization deterministic, finite, and improves its own objective',()=>{const baseline=G.candidate(667,demo),a=O.optimize(demo,undefined,[],913,36,baseline),b=O.optimize(demo,undefined,[],913,36,baseline);assert.deepEqual(a,b);assert.ok(Number.isFinite(a.metrics.score));assert.ok(a.metrics.score>=O.evaluate(baseline,demo).score-1e-5)});
test('actual responses change neighborhood success predictions',()=>{const c=G.candidate(41,demo),m=O.evaluate(c,demo);const record={id:'1',candidate:c,metrics:m,expected:'A',response:'A',correct:true,blank:false,rt:600,at:'test'};const prior=G.empiricalPrediction(c,[]).p,good=G.empiricalPrediction(c,[record]).p,bad=G.empiricalPrediction(c,[{...record,correct:false}]).p;assert.ok(good>prior);assert.ok(bad<prior)});
test('observer fitting acknowledges insufficient data',()=>{const p=A.fitVision([]);assert.match(p.label,/Uncertain/);assert.equal(p.confidence,'limited')});
