const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..');
let tsPath;try{tsPath=require.resolve('typescript/bin/tsc');}catch{const available='/usr/local/slides_js/node_modules/typescript/bin/tsc';if(fs.existsSync(available))tsPath=available;else{console.error('Run npm install first. The prebuilt index.html does not need a build.');process.exit(1);}}
cp.execFileSync(process.execPath,[tsPath,'--project',path.join(root,'tsconfig.json')],{stdio:'inherit'});
const modules={};function walk(dir){for(const f of fs.readdirSync(dir)){const full=path.join(dir,f);if(fs.statSync(full).isDirectory())walk(full);else if(f.endsWith('.js'))modules[path.relative(path.join(root,'build'),full).replaceAll('\\','/').slice(0,-3)]=fs.readFileSync(full,'utf8');}}walk(path.join(root,'build'));
function bundle(entry){return `(function(){'use strict';const modules={${Object.entries(modules).map(([name,code])=>JSON.stringify(name)+':function(module,exports,require){\n'+code+'\n}').join(',\n')}};const cache={};function resolve(from,id){if(!id.startsWith('.'))return id;const parts=from.split('/');parts.pop();for(const p of id.split('/')){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);}return parts.join('/');}function load(id){if(cache[id])return cache[id].exports;const m={exports:{}};cache[id]=m;if(!modules[id])throw Error('Missing module '+id);modules[id](m,m.exports,q=>load(resolve(id,q)));return m.exports;}load(${JSON.stringify(entry)});})();`;}
const escapeScript=s=>s.replace(/<\/script/gi,'<\\/script');
const worker=bundle('optimizer/worker'),app=bundle('App');
const vendors=['react.production.min.js','react-dom.production.min.js'].map(f=>fs.readFileSync(path.join(root,'public',f),'utf8')).join('\n');
const css=fs.readFileSync(path.join(root,'src/styles.css'),'utf8');
const notices=fs.readFileSync(path.join(root,'THIRD_PARTY_NOTICES.txt'),'utf8').replace(/--/g,'- -');
const html=`<!DOCTYPE html><!--\n${notices}\n--><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: blob:; worker-src blob:; connect-src 'none'; font-src 'none'; base-uri 'none'; form-action 'none'"><meta name="description" content="A local-only experimental laboratory for personalized color-vision camouflage. Not a diagnosis or a secrecy guarantee."><title>Chromasecret - A personal perception experiment</title><style>${css}</style></head><body><div id="root"></div><noscript>Chromasecret needs JavaScript for local canvas experiments. No data is uploaded.</noscript><script>${escapeScript(vendors)}</script><script>window.CHROMASECRET_WORKER=${JSON.stringify(worker).replace(/<\//g,'<\\/')};</script><script>${escapeScript(app)}</script></body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html);
fs.mkdirSync(path.join(root,'dist'),{recursive:true});fs.writeFileSync(path.join(root,'dist/index.html'),html);
console.log('Built self-contained offline app:',(Buffer.byteLength(html)/1024).toFixed(0),'KiB');
